version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: subscriptions_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: subscriptions_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4
    container_name: subscriptions_redis
    restart: unless-stopped
    command: redis-server --requirepass redis123 --save 60 1 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: