server:
  host: "0.0.0.0"
  port: 8080

database:
  host: "localhost"
  port: 5433
  user: "postgres"
  password: "postgres123"
  dbname: "subscriptions_db"
  sslmode: "disable"

app:
  log_level: "debug"